@Loyalty_HostAddress = http://localhost:5281
@Loyalty_ApiKey = dev-loyalty-api-key

### Create program
POST {{Loyalty_HostAddress}}/api/programs
X-Loyalty-Api-Key: {{Loyalty_ApiKey}}
Content-Type: application/json

{
  "id": "summer-2026",
  "title": "Summer promo",
  "description": "First loyalty program",
  "state": "Active",
  "startDate": "2026-06-01T00:00:00Z",
  "finishDate": "2026-08-31T23:59:59Z",
  "minTransactionAmount": 10,
  "maxTransactionAmount": 10000,
  "achievement": {
    "id": "first-bonus",
    "transactionsCountToApplyAchievement": 1,
    "reward": {
      "id": "bonus-percent",
      "amount": 5,
      "type": "Percent",
      "target": "Bonus",
      "usageType": "Add"
    }
  },
  "createdBy": "esidina"
}

###

### Get all programs
GET {{Loyalty_HostAddress}}/api/programs
X-Loyalty-Api-Key: {{Loyalty_ApiKey}}

###

### Get program
GET {{Loyalty_HostAddress}}/api/programs/summer-2026
X-Loyalty-Api-Key: {{Loyalty_ApiKey}}

###

### Update program
PUT {{Loyalty_HostAddress}}/api/programs/summer-2026
X-Loyalty-Api-Key: {{Loyalty_ApiKey}}
Content-Type: application/json

{
  "title": "Summer promo updated",
  "description": "Updated loyalty program",
  "state": "Active",
  "startDate": "2026-06-01T00:00:00Z",
  "finishDate": "2026-09-30T23:59:59Z",
  "minTransactionAmount": 20,
  "maxTransactionAmount": 15000,
  "achievement": {
    "id": "first-bonus",
    "transactionsCountToApplyAchievement": 2,
    "reward": {
      "id": "bonus-percent",
      "amount": 10,
      "type": "Percent",
      "target": "Bonus",
      "usageType": "Add"
    }
  },
  "updatedBy": "esidina"
}

###

### Delete program
DELETE {{Loyalty_HostAddress}}/api/programs/summer-2026
X-Loyalty-Api-Key: {{Loyalty_ApiKey}}
Content-Type: application/json

{
  "updatedBy": "esidina"
}

###

### Mongo health
GET {{Loyalty_HostAddress}}/health

###
